spring.application.name=ecommerce-backend

## MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/ecommerce}
spring.data.mongodb.database=ecommerce

## JWT
jwt.secret=${JWT_SECRET:Sjdh92nD82mslaKQw92mZlaWoqpM29dkWkams0283nZlPqPqLmZx92kaQmZx1As}
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

## Razorpay
razorpay.key-id=${RAZORPAY_KEY_ID:rzp_test_SeXYBlKUUUINyd}
razorpay.key-secret=${RAZORPAY_KEY_SECRET:czVjcfTItcXq1boXic2YXMaK}
razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET:czVjcfTItcXq1boXic2YXMaK}

## Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=ecommerce-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.ecommerce_backend.events
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

## Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.timeout=2000ms

## Cache
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
